import type { Project, Service, Stat } from "./types";

export const projects: Project[] = [
  {
    id: "eslam-fitness",
    title: "Islam Fitness",
    category: "Landing Page",
    price: 199,
    customPrice: 599,
    description: "A professional fitness coaching platform for elite trainers. Features dynamic training packages and WhatsApp lead capture with a clean, high-performance layout.",
    tags: ["React", "Tailwind", "Vite"],
    gradient: "from-zinc-900 to-black",
    accentColor: "#22c55e",
    features: [
      "Dark luxury fitness UI",
      "WhatsApp lead integration",
      "Dynamic pricing plans",
      "Transformation gallery",
      "Mobile-first design",
    ],
    useCase: "Ideal for elite personal trainers and fitness coaches.",
    liveDemo: "https://eslam-eight.vercel.app/#home",
    image: "https://image.thum.io/get/width/800/crop/600/https://eslam-eight.vercel.app/",
    upsells: { customization: 150, hosting: 25, maintenance: 80 },
  },
  {
    id: "luxecart-pro",
    title: "LuxeCart Pro",
    category: "E-commerce",
    price: 299,
    customPrice: 799,
    description: "A high-conversion e-commerce storefront designed for luxury brands. Includes a streamlined checkout flow and a focus on visual storytelling.",
    tags: ["Next.js", "Stripe", "MongoDB"],
    gradient: "from-blue-600 to-cyan-600",
    accentColor: "#0077b6",
    features: [
      "AI product recommendations",
      "One-click checkout",
      "Inventory dashboard",
      "Mobile-first design",
      "Multi-currency support",
      "Analytics dashboard",
    ],
    useCase: "Perfect for fashion brands, luxury goods stores, and high-ticket product retailers.",
    liveDemo: "#",
    upsells: { customization: 200, hosting: 30, maintenance: 99 },
  },
  {
    id: "fitforge",
    title: "FitForge",
    category: "Landing Page",
    price: 149,
    customPrice: 499,
    description: "A cinematic fitness brand landing page with parallax effects, animated stats, and WhatsApp lead capture. Converts visitors into paying clients.",
    tags: ["React", "GSAP", "Tailwind"],
    gradient: "from-cyan-600 to-blue-600",
    accentColor: "#00d4ff",
    features: [
      "Parallax hero section",
      "Animated statistics",
      "WhatsApp integration",
      "Transformation gallery",
      "Pricing tables",
      "Contact form",
    ],
    useCase: "Ideal for personal trainers, gyms, fitness coaches, and wellness brands.",
    liveDemo: "#",
    upsells: { customization: 150, hosting: 25, maintenance: 79 },
  },
  {
    id: "novacorp",
    title: "NovaCorp",
    category: "Corporate",
    price: 199,
    customPrice: 699,
    description: "A sleek corporate website with glassmorphism UI, smooth scroll animations, and a powerful team showcase. Makes your business look like a Fortune 500.",
    tags: ["Next.js", "Framer Motion", "GSAP"],
    gradient: "from-emerald-600 to-teal-600",
    accentColor: "#10b981",
    features: [
      "Glassmorphism UI",
      "Team showcase",
      "Services section",
      "Client testimonials",
      "Blog integration",
      "Contact & maps",
    ],
    useCase: "Great for agencies, consulting firms, tech companies, and startups.",
    liveDemo: "#",
    upsells: { customization: 180, hosting: 30, maintenance: 89 },
  },
  {
    id: "restaurantx",
    title: "RestaurantX",
    category: "Business",
    price: 249,
    customPrice: 749,
    description: "A mouth-watering restaurant website with online reservations, cinematic food photography layout, and seamless delivery integration.",
    tags: ["Next.js", "Stripe", "Tailwind"],
    gradient: "from-orange-600 to-rose-600",
    accentColor: "#f97316",
    features: [
      "Online reservations",
      "Menu showcase",
      "Food photography layout",
      "Location & hours",
      "Reviews section",
      "Delivery integration",
    ],
    useCase: "Perfect for restaurants, cafes, food delivery services, and catering businesses.",
    liveDemo: "#",
    upsells: { customization: 200, hosting: 30, maintenance: 99 },
  },
  {
    id: "pixelflow",
    title: "PixelFlow Agency",
    category: "Business",
    price: 349,
    customPrice: 999,
    description: "An award-worthy creative agency portfolio with 3D card effects, dynamic project showcases, and an integrated booking system built to win clients.",
    tags: ["Next.js", "Three.js", "Framer Motion"],
    gradient: "from-blue-500 to-cyan-500",
    accentColor: "#00b4d8",
    features: [
      "3D card interactions",
      "Project showcase",
      "Client booking system",
      "Case studies",
      "Video backgrounds",
      "Award animations",
    ],
    useCase: "Designed for creative agencies, design studios, and freelance professionals.",
    liveDemo: "#",
    upsells: { customization: 250, hosting: 35, maintenance: 120 },
  },
  {
    id: "cryptovault",
    title: "CryptoVault",
    category: "Apps",
    price: 499,
    customPrice: 1499,
    description: "A full-featured crypto dashboard with real-time price tracking, portfolio management, and a sleek dark fintech UI. The future of finance.",
    tags: ["React", "Node.js", "WebSocket"],
    gradient: "from-yellow-500 to-orange-600",
    accentColor: "#f59e0b",
    features: [
      "Real-time price tracking",
      "Portfolio management",
      "Price alerts",
      "News feed",
      "Trading chart",
      "Multi-wallet support",
    ],
    useCase: "Ideal for crypto projects, fintech startups, and blockchain companies.",
    liveDemo: "#",
    upsells: { customization: 400, hosting: 50, maintenance: 150 },
  },
];

export const categories = ["All", "E-commerce", "Landing Page", "Corporate", "Business", "Apps"] as const;

export const services: Service[] = [
  {
    name: "Basic",
    price: "$99 – $299",
    tagline: "Quick edits & fixes",
    color: "from-slate-800 to-slate-700",
    accentColor: "rgba(148,163,184,0.5)",
    features: [
      "Content updates",
      "Minor design tweaks",
      "Bug fixes",
      "Performance tuning",
      "SEO setup",
      "1 revision round",
    ],
    disabled: ["Custom design", "New features", "Priority support"],
    cta: "Get Started",
  },
  {
    name: "Standard",
    price: "$499 – $1,200",
    tagline: "Template customization",
    color: "from-blue-800 to-cyan-800",
    accentColor: "rgba(0,119,182,0.6)",
    featured: true,
    features: [
      "Full template customization",
      "Brand identity integration",
      "Custom color scheme",
      "Content writing",
      "Mobile optimization",
      "3 revision rounds",
      "1 month support",
    ],
    disabled: ["Full custom design"],
    cta: "Most Popular",
  },
  {
    name: "Premium",
    price: "$2,000+",
    tagline: "Full custom build",
    color: "from-cyan-800 to-blue-800",
    accentColor: "rgba(0,212,255,0.5)",
    features: [
      "100% custom design",
      "Full-stack development",
      "Advanced animations",
      "CMS integration",
      "E-commerce features",
      "Unlimited revisions",
      "3 months support",
      "SEO + Analytics",
      "Hosting setup",
    ],
    disabled: [],
    cta: "Let's Build",
  },
];

export const stats: Stat[] = [
  { label: "Projects Handcrafted", value: "84", suffix: "+" },
  { label: "Avg. Response Time", value: "2", suffix: "h" },
  { label: "Industries Served", value: "12", suffix: "+" },
  { label: "Client Satisfaction", value: "98", suffix: "%" },
];

export const testimonials = [
  {
    name: "Omar F.",
    role: "Gym Owner",
    content: "Nexoura transformed our local gym's presence into a digital powerhouse. The attention to detail is insane.",
  },
  {
    name: "Sarah M.",
    role: "Retail Brand Manager",
    content: "Fast, reliable, and actually cares about the business results, not just the code. Highly recommended.",
  },
];
